### ISSUE TITLE
JSON returned by Eventbrite not parseable by Crack::JSON

### ISSUE THREAD

**Issue by jimm** [ryanj/eventbrite-client.rb#2]
When I run "response = client.user_list_events()" an error is thrown because Crack::JSON.parse can not parse string values like "2012-04-02 07:20:42" that have colons in them. To work around this, I first require the standard json gem and replace HTTParty's JSON parse method like this:

```
module HTTParty
  class Parser
    def json
      # Replace Crack::JSON with JSON because Crack::JSON barfs on the JSON
      # returned by Eventbrite (for example, values that are strings with
      # colons in them such as datetimes like "2012-04-02 07:20:42").
      JSON.parse(body)
    end
  end
end
```

I'm running Ruby 1.9.4, eventbrite-client 0.1.0, httparty 0.7.8, and crack 0.1.8.

**Comment by ryanj** [comment]
Nice work-around, this also seems to work:

```
YAML::ENGINE.yamler = 'syck'
```

It looks like a bug in 'psych.rb'
See [Issue 1](https://github.com/ryanjarvinen/eventbrite-client.rb/issues/1)

**Comment by ryanj** [comment]
Thanks for reporting this!

**Comment by ryanj** [comment]
I've updated the httparty dependency to 0.8+
The latest version of this gem should fix any JSON parsing issues.

**Comment by ryanj** [comment]
I've updated the httparty dependency to 0.8+
The latest version of this gem should fix any JSON parsing issues.
