### ISSUE TITLE
Ruby 1.8 hash syntax

### ISSUE THREAD

**Issue by yrashk** [ryanj/eventbrite-client.rb#5]
Hi,

Would you consider merging this https://github.com/jlsync/eventbrite-client.rb/commit/70a92265fa88b24568b647ac4694092ea7da123d in?

**Comment by ryanj** [comment]
Sounds like a good idea. Thanks for the suggestion!

**Comment by ryanj** [comment]
This change should now be available via "gem install eventbrite-client".
Thanks again - Let me know if you find any other issues!
