### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by Floppy** [ryanj/eventbrite-client.rb#8]
Versions are very inconsistent.

VERSION says 0.1.0.
gemspec says 0.1.3.
rubygems has 0.1.4 listed.

I have submitted a PR to the eventbrite repo to update HTTParty, but I have no idea if the code there is the latest, because of this confusion. Who is maintaining this project now?

**Comment by ryanj** [comment]
Sorry, I've stopped development on this project.
It targets an older version of the Eventbrite API, so it's mostly just around for historical purposes.  I'd ask the Eventbrite team if they have a newer API client lib or SDK that they can recommend.

**Comment by Floppy** [comment]
OK, thanks for letting me know!
